// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svicrvtyqkdyclypfxxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2aWNydnR5cWtkeWNseXBmeHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0NjUyMzksImV4cCI6MjA5MzA0MTIzOX0.PUsQpjTnCuKWks_e6ESPwhqr7GlID8Zi5rhDmPqtAPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});